name: Build AutoGPTQ ROCm 5.4.2 Wheels

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build ROCm wheel for Python ${{ matrix.pyver }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pyver: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'are-we-gfx1100-yet/AutoGPTQ-rocm'
      - uses: actions/checkout@v3
        with:
          repository: 'ROCmSoftwarePlatform/rocPRIM'
          ref: 'rocm-5.4.2'
          path: 'rocPRIM'
      - uses: actions/checkout@v3
        with:
          repository: 'ROCmSoftwarePlatform/rocThrust'
          ref: 'rocm-5.4.2'
          path: 'rocThrust'
          
      - name: Install ROCm SDK 5.4.2
        run: |
          sudo apt update
          wget https://repo.radeon.com/amdgpu-install/5.4.2/ubuntu/focal/amdgpu-install_5.4.50402-1_all.deb
          sudo dpkg -i amdgpu-install_5.4.50402-1_all.deb
          sudo DEBIAN_FRONTEND=noninteractive amdgpu-install --usecase=rocm --no-dkms --no-32 -y
          echo "/opt/rocm/bin" >> $GITHUB_PATH
          echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
          
      - name: Install rocPRIM
        run: |
          cd rocPRIM
          mkdir build
          cd build
          CXX=hipcc cmake -DAMDGPU_TARGETS="gfx900:xnack-;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack-;gfx90a:xnack+;gfx1030" ../.
          make -j4
          sudo make install
          
      - name: Install rocThrust
        run: |
          cd rocThrust
          mkdir build
          cd build
          CXX=hipcc cmake -DAMDGPU_TARGETS="gfx900:xnack-;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack-;gfx90a:xnack+;gfx1030" ../.
          make -j4
          make package
          sudo make install
        
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}
        
      - name: Install GPTQ Dependencies
        run: |
          pip3 install sentencepiece build wheel ninja transformers==4.30.2 datasets safetensors==0.3.1 accelerate==0.20.3 torch==2.0.1+rocm5.4.2 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2
        
      - name: Build Wheel
        run: |
          cp 'setup_rocm.py' 'setup.py'
          python3 -m build -n --wheel -C--build-option=egg_info "-C--build-option=--tag-build=+rocm5.4.2"
        
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
