name: Build Wheels For Oobabooga

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build ${{ matrix.os }} wheel for Python ${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        pyver: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'oobabooga/GPTQ-for-LLaMa'
        
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}
        
      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: "build"
          python-version: ${{ matrix.pyver }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          add-pip-as-python-dependency: true
          auto-activate-base: false
          
      - name: Install Dependencies
        run: |
          mamba install -y 'cuda' -c 'nvidia/label/cuda-11.7.0'
          python -m pip install build wheel ninja transformers==4.30.2 datasets safetensors==0.3.1 accelerate==0.20.3 sentencepiece "torch==2.0.1+cu117" torchvision torchaudio --extra-index-url "https://download.pytorch.org/whl/cu117"
        
      - name: Build Wheel
        run: |
          $env:CUDA_PATH = $env:CONDA_PREFIX
          $env:CUDA_HOME = $env:CONDA_PREFIX
          if ($IsLinux) {$env:LD_LIBRARY_PATH = $env:CONDA_PREFIX + '/lib:' + $env:LD_LIBRARY_PATH}
          $env:TORCH_CUDA_ARCH_LIST = '6.0 6.1 7.0 7.5 8.0 8.6+PTX'
          cp 'setup_cuda.py' 'setup.py'
          python -m build -n --wheel
        
      - uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: 'linux-wheels'
          path: ./dist/*.whl
        
      - uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: 'windows-wheels'
          path: ./dist/*.whl