name: Build ROCm Wheel for oobabooga

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheel for ROCm
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'oobabooga/GPTQ-for-LLaMa'
          ref: 'cuda'
          
      - name: Install ROCm SDK
        run: |
          sudo apt update
          wget https://repo.radeon.com/amdgpu-install/5.4.2/ubuntu/focal/amdgpu-install_5.4.50402-1_all.deb
          sudo dpkg -i amdgpu-install_5.4.50402-1_all.deb
          sudo DEBIAN_FRONTEND=noninteractive amdgpu-install --usecase=rocm --rocmrelease=5.4.2 --no-dkms --no-32 -y
          echo "/opt/rocm-5.4.2/bin" >> $GITHUB_PATH
        
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        
      - name: Install GPTQ Dependencies
        run: |
          pip3 install sentencepiece build wheel ninja transformers==4.30.2 datasets safetensors==0.3.1 accelerate==0.20.3 torch==2.0.1+rocm5.4.2 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2
        
      - name: Build Wheel
        run: |
          cp 'setup_cuda.py' 'setup.py'
          python3 -m build -n --wheel
        
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
